FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/*


RUN wget -O /tmp/chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chrome-linux64.zip \
    && unzip /tmp/chrome-linux64.zip -d /opt/google \
    && ln -s /opt/google/chrome-linux64/chrome /usr/bin/google-chrome


RUN wget -O /tmp/chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chromedriver-linux64.zip \
    && unzip /tmp/chromedriver-linux64.zip -d /usr/local/bin \
    && chmod +x /usr/local/bin/chromedriver


COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt


WORKDIR /app
COPY . /app


ENV PATH="/usr/local/bin:${PATH}"


CMD ["python3", "tests/test_app.py"]
